title: "Sudesh Naidoo"
email: @gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is an E-portfolio of evidence and discussions held during my Network Security Module at Essex University.
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/E-portfolio-Network Security Module"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://sudesh74.github.io" 
twitter_username: 
github_username: Sudesh74
form_url: "https://Networsec Module.io/f/xrgodpqo"
#social_image: # add image link
#social_image_alt: # Alt text for the link preview image
#google_analytics_measurement_id: # G-XXXXXXXXXX

#sass:
  #sass_dir: 

#icon: ./assets/img/icon.jpg
